// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using invetario_api.database;

#nullable disable

namespace invetario_api.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20260105062533_images-names")]
    partial class imagesnames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("invetario_api.Modules.categories.entity.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoryId"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("categoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("invetario_api.Modules.client.entity.Client", b =>
                {
                    b.Property<int>("clientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("clientId"));

                    b.Property<int>("clientType")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("documentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<string>("typeDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("clientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("invetario_api.Modules.entryorder.entity.EntryOrderDetail", b =>
                {
                    b.Property<int>("entryOrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("entryOrderDetailId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("entryOrderDetailStatus")
                        .HasColumnType("int");

                    b.Property<int>("entryOrderId")
                        .HasColumnType("int");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<float>("unitPrice")
                        .HasColumnType("real");

                    b.HasKey("entryOrderDetailId");

                    b.HasIndex("entryOrderId");

                    b.HasIndex("productId");

                    b.ToTable("EntryOrderDetails");
                });

            modelBuilder.Entity("invetario_api.Modules.entryorder.entity.Entryorder", b =>
                {
                    b.Property<int>("entryOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("entryOrderId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("entryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("entryOrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("entryOrderType")
                        .HasColumnType("int");

                    b.Property<string>("observation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("payCondition")
                        .HasColumnType("int");

                    b.Property<int>("providerId")
                        .HasColumnType("int");

                    b.Property<int>("storeId")
                        .HasColumnType("int");

                    b.Property<float>("tax")
                        .HasColumnType("real");

                    b.Property<string>("typeMoney")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("entryOrderId");

                    b.HasIndex("providerId");

                    b.HasIndex("storeId");

                    b.ToTable("EntryOrders");
                });

            modelBuilder.Entity("invetario_api.Modules.images.entity.Images", b =>
                {
                    b.Property<int>("imageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("imageId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("imageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("imageId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("invetario_api.Modules.products.entity.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productId"));

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codeInternal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("imageId")
                        .HasColumnType("int");

                    b.Property<int>("minStock")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("priceBuy")
                        .HasColumnType("real");

                    b.Property<float>("priceSell")
                        .HasColumnType("real");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<int>("unitId")
                        .HasColumnType("int");

                    b.HasKey("productId");

                    b.HasIndex("categoryId");

                    b.HasIndex("imageId");

                    b.HasIndex("unitId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("invetario_api.Modules.products.entity.ProductStore", b =>
                {
                    b.Property<int>("productStoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productStoreId"));

                    b.Property<int>("actualStock")
                        .HasColumnType("int");

                    b.Property<int>("availableStock")
                        .HasColumnType("int");

                    b.Property<float>("avgCost")
                        .HasColumnType("real");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("lastCost")
                        .HasColumnType("real");

                    b.Property<int>("maxStock")
                        .HasColumnType("int");

                    b.Property<int>("minStock")
                        .HasColumnType("int");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("reservedStock")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<int>("storeId")
                        .HasColumnType("int");

                    b.HasKey("productStoreId");

                    b.HasIndex("productId");

                    b.HasIndex("storeId");

                    b.ToTable("Product_Store");
                });

            modelBuilder.Entity("invetario_api.Modules.provider.entity.Provider", b =>
                {
                    b.Property<int>("providerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("providerId"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("daysDelivery")
                        .HasColumnType("int");

                    b.Property<string>("documentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mainContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("payCondition")
                        .HasColumnType("int");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("publicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<string>("typeDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeMoney")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("providerId");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("invetario_api.Modules.store.entity.Store", b =>
                {
                    b.Property<int>("storeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("storeId"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("maxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("observations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("storeId");

                    b.HasIndex("userId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("invetario_api.Modules.unit.entity.Unit", b =>
                {
                    b.Property<int>("unitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("unitId"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("unitId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("invetario_api.Modules.users.entity.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("invetario_api.Modules.entryorder.entity.EntryOrderDetail", b =>
                {
                    b.HasOne("invetario_api.Modules.entryorder.entity.Entryorder", "entryorder")
                        .WithMany("entryOrderDetails")
                        .HasForeignKey("entryOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invetario_api.Modules.products.entity.Product", "product")
                        .WithMany("entryOrderDetails")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("entryorder");

                    b.Navigation("product");
                });

            modelBuilder.Entity("invetario_api.Modules.entryorder.entity.Entryorder", b =>
                {
                    b.HasOne("invetario_api.Modules.provider.entity.Provider", "provider")
                        .WithMany("entryOrders")
                        .HasForeignKey("providerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invetario_api.Modules.store.entity.Store", "store")
                        .WithMany("entryOrders")
                        .HasForeignKey("storeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("provider");

                    b.Navigation("store");
                });

            modelBuilder.Entity("invetario_api.Modules.products.entity.Product", b =>
                {
                    b.HasOne("invetario_api.Modules.categories.entity.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invetario_api.Modules.images.entity.Images", "image")
                        .WithMany("products")
                        .HasForeignKey("imageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invetario_api.Modules.unit.entity.Unit", "unit")
                        .WithMany("products")
                        .HasForeignKey("unitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");

                    b.Navigation("image");

                    b.Navigation("unit");
                });

            modelBuilder.Entity("invetario_api.Modules.products.entity.ProductStore", b =>
                {
                    b.HasOne("invetario_api.Modules.products.entity.Product", "product")
                        .WithMany("productStores")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invetario_api.Modules.store.entity.Store", "store")
                        .WithMany("productStores")
                        .HasForeignKey("storeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("store");
                });

            modelBuilder.Entity("invetario_api.Modules.store.entity.Store", b =>
                {
                    b.HasOne("invetario_api.Modules.users.entity.User", "user")
                        .WithMany("stores")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("invetario_api.Modules.categories.entity.Category", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("invetario_api.Modules.entryorder.entity.Entryorder", b =>
                {
                    b.Navigation("entryOrderDetails");
                });

            modelBuilder.Entity("invetario_api.Modules.images.entity.Images", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("invetario_api.Modules.products.entity.Product", b =>
                {
                    b.Navigation("entryOrderDetails");

                    b.Navigation("productStores");
                });

            modelBuilder.Entity("invetario_api.Modules.provider.entity.Provider", b =>
                {
                    b.Navigation("entryOrders");
                });

            modelBuilder.Entity("invetario_api.Modules.store.entity.Store", b =>
                {
                    b.Navigation("entryOrders");

                    b.Navigation("productStores");
                });

            modelBuilder.Entity("invetario_api.Modules.unit.entity.Unit", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("invetario_api.Modules.users.entity.User", b =>
                {
                    b.Navigation("stores");
                });
#pragma warning restore 612, 618
        }
    }
}
